language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
env:
  - DOCUMENTER_DEBUG="true"
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("Arrows")'
  - julia -e 'Pkg.build("Plots")'
  - julia -e 'Pkg.build("Luxor")'
  - julia -e 'Pkg.test("Arrows", coverage=true)'
after_success:
  # - julia -e 'cd(Pkg.dir("Arrows")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Arrows")); include(joinpath("docs", "make.jl"))'
matrix:
  allow_failures:
    - julia: nightly
